#!/usr/bin/env bash
# Filename:      etc/bash/bash.Darwin.d/10_functions
# Last modified: 2016.03.05


# calculator
function ?()
{
    echo "$*" | bc --mathlib
}


# configure less to show man pages in color
function man()
{
    env LESS_TERMCAP_mb=$'\e[1;31m' \
        LESS_TERMCAP_md=$'\e[1;31m' \
        LESS_TERMCAP_me=$'\e[0m' \
        LESS_TERMCAP_se=$'\e[0m' \
        LESS_TERMCAP_so=$'\e[1;44;33m' \
        LESS_TERMCAP_ue=$'\e[0m' \
        LESS_TERMCAP_us=$'\e[1;32m' \
        man "$@"
}
