#!/usr/bin/env bash
# Filename:      etc/bashrc.Darwin.d/00_aliases
# Last modified: 2016.03.08


alias egrep="gegrep --binary-files=without-match --color=auto --directories=skip"
alias fgrep="gfgrep --binary-files=without-match --color=auto --directories=skip"
alias findx="find . -type d \( -name '.svn' -o -name '.git' \) -prune -o -type f -print0 | xargs -0 ggrep --binary-files=without-match --color=auto --no-messages"
alias findxc="find . -type d \( -name '.svn' -o -name '.git' \) -prune -o -type f -and \( -name '*.cpp' -o -name '*.hpp' -o -name '*.c' -o -name '*.h' \) -print0 | xargs -0 ggrep --binary-files=without-match --color=auto --no-messages"
alias findxpy="find . -type d \( -name '.svn' -o -name '.git' \) -prune -o -type f -and \( -name '*.py' \) -print0 | xargs -0 ggrep --binary-files=without-match --color=auto --no-messages"
alias g="ggrep --binary-files=without-match --color=auto --directories=skip"
alias gerp="ggrep --binary-files=without-match --color=auto --directories=skip"
alias grep="ggrep --binary-files=without-match --color=auto --directories=skip"
alias nsg="netstat --all --numeric --program | ggrep --color=auto"
alias psg="ps -Lef | ggrep --invert-match ggrep | ggrep --color=auto"
