#!/usr/bin/env bash
# Filename:      etc/bashrc.Darwin.d/00_aliases
# Last modified: 2016.03.08


# load the bash completion scripts if they're available
if [[ -d /usr/local/etc/bash_completion.d ]]; then
    for file in /usr/local/etc/bash_completion.d/*; do
        [[ -x "${file}" ]] && source "${file}"
    done
    unset file
fi
