#!/usr/bin/env bash
# Filename:      etc/bash/bash.Linux.d/00_aliases
# Last modified: 2016.03.07


alias egrep='egrep --binary-files=without-match --color=auto --directories=skip'
alias fgrep='fgrep --binary-files=without-match --color=auto --directories=skip'
alias findx='find . -type d \( -name ".svn" -o -name ".git" \) -prune -o -type f -print0 | xargs -0 grep --binary-files=without-match --color=auto --no-messages'
alias findxc='find . -type d \( -name ".svn" -o -name ".git" \) -prune -o -type f -and \( -name "*.cpp" -o -name "*.hpp" -o -name "*.c" -o -name "*.h" \) -print0 | xargs -0 grep --binary-files=without-match --color=auto --no-messages'
alias findxpy='find . -type d \( -name ".svn" -o -name ".git" \) -prune -o -type f -and \( -name "*.py" \) -print0 | xargs -0 grep --binary-files=without-match --color=auto --no-messages'
alias g='grep --binary-files=without-match --color=auto --directories=skip --line-number'
alias gerp='grep --binary-files=without-match --color=auto --directories=skip --line-number'
alias grep='grep --binary-files=without-match --color=auto --directories=skip --line-number'
alias nsg='netstat --all --numeric --program | grep --color=auto --line-number'
alias psg='ps -Lef | grep --invert-match grep | grep --color=auto --line-number'
