#!/usr/bin/env bash
# Filename:      etc/bash/bash.Linux.d/20_ps1
# Last modified: 2016.03.05


# __git_ps1 shell prompt settings
GIT_PS1_SHOWCOLORHINTS=true
GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
export PS1='\u@\h \W$(__git_ps1 " (\[\033[0;32m\]%s\[\033[0m\])")\$ '
