#!/usr/bin/env bash
# Filename:      etc/bash/bash.Linux.d/10_functions
# Last modified: 2016.03.08


# calculator
?()
{
    echo "$*" | bc --mathlib
}


# show bash colors
colors()
{
    for i in {0..255}; do
        echo -e "\e[38;05;${i}m${i}"
    done | column -c 80 -s "  "
    echo -e "\e[m"
    unset i
}


# configure less to show man pages in color
man()
{
    env LESS_TERMCAP_mb=$'\e[1;31m' \
        LESS_TERMCAP_md=$'\e[1;31m' \
        LESS_TERMCAP_me=$'\e[0m' \
        LESS_TERMCAP_se=$'\e[0m' \
        LESS_TERMCAP_so=$'\e[1;44;33m' \
        LESS_TERMCAP_ue=$'\e[0m' \
        LESS_TERMCAP_us=$'\e[1;32m' \
        man "$@"
}


# prints the largest debs installed
installed()
{
    dpkg-query --show --showformat='${Installed-Size}\t${Package}\n' | sort --numeric-sort
}
