#!/usr/bin/env bash
# Filename:      etc/bash/bash.Linux.d/10_functions
# Last modified: 2016.03.10


# show bash colors
colors()
{
    for i in {0..255}; do
        echo -e "\e[38;05;${i}m${i}"
    done | column -c 80 -s "  "
    echo -e "\e[m"
    unset i
}


# prints the largest debs installed
installed()
{
    dpkg-query --show --showformat='${Installed-Size}\t${Package}\n' | sort --numeric-sort
}
