#!/usr/bin/env bash
# Filename:      etc/bash_profile.Darwin.d/00_path
# Last modified: 2016.03.07

export PATH="${HOME}/bin:${HOME}/local/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/sbin:/sbin:${PATH}"
export MANPATH="${HOME}/local/man:/usr/local/opt/coreutils/libexec/gnuman:/usr/local/share/man:${MANPATH}"
