# Filename:      etc/bash/bashrc
# Last modified: 2016.04.26
#
# This file is only sourced by interactive non-login shells.

#set -x

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]$PWD\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt


# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi


# ls aliases
alias  l="ls --color=auto --group-directories-first --quoting-style=literal"
alias la="ls -l --all --classify --color=auto --group-directories-first --human-readable --quoting-style=literal"
alias ll="ls -l --classify --color=auto --group-directories-first --human-readable --quoting-style=literal"
alias lr="ls -lt --all --color=auto --group-directories-first --human-readable --quoting-style=literal --reverse"
alias ls="ls --color=auto --group-directories-first --quoting-style=literal"
alias sl="ls --color=auto --group-directories-first --quoting-style=literal"

# make aliases
alias   m="make"
alias  mc="make clean"
alias mdc="make distclean"
alias mcm="make clean && make"

# vim aliases
alias  vi="vim -O"
alias vim="vim -O"
alias vmi="vim -O"

alias cp="cp --interactive"
alias dc="cd"
alias df="df --human-readable"
alias dul="du --human-readable --summarize * | sort --human-numeric-sort --reverse"
alias free="free --mega"
alias loc="locate --database=${HOME}/var/mlocate/mlocate.db"
alias lsof_net="lsof -P -i 4 -n"
alias mount="mount | column -t"
alias mv="mv --interactive"
alias ns="netstat --numeric --tcp --all --udp --program --listening"
alias psc="ps xawf -eo pid,user,cgroup,args"
alias rmdirr="find . -type d -empty -delete"


# calculator
calc()
{
    echo "$*" | bc --mathlib
} 
# configure less to show man pages in color
man()
{
    env LESS_TERMCAP_mb=$'\e[1;31m' \
        LESS_TERMCAP_md=$'\e[1;31m' \
        LESS_TERMCAP_me=$'\e[0m' \
        LESS_TERMCAP_se=$'\e[0m' \
        LESS_TERMCAP_so=$'\e[1;44;33m' \
        LESS_TERMCAP_ue=$'\e[0m' \
        LESS_TERMCAP_us=$'\e[1;32m' \
        man "$@"
}


# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# if the bashrc.d directory exists, source everything in there
if [[ -d "${HOME}/etc/bash/bashrc.$(uname).d" ]]; then
    for file in ${HOME}/etc/bash/bashrc.$(uname).d/*; do
        source "${file}"
    done
    unset file
fi

echo $PS1

