# Filename:      etc/bash/bashrc
# Last modified: 2016.04.26
#
# This file is only sourced by interactive non-login shells.


# ls aliases
alias  l="ls --color=auto --group-directories-first --quoting-style=literal"
alias la="ls -l --all --classify --color=auto --group-directories-first --human-readable --quoting-style=literal"
alias ll="ls -l --classify --color=auto --group-directories-first --human-readable --quoting-style=literal"
alias lr="ls -lt --all --color=auto --group-directories-first --human-readable --quoting-style=literal --reverse"
alias ls="ls --color=auto --group-directories-first --quoting-style=literal"
alias sl="ls --color=auto --group-directories-first --quoting-style=literal"

# make aliases
alias   m="make"
alias  mc="make clean"
alias mdc="make distclean"
alias mcm="make clean && make"

# vim aliases
alias  vi="vim -O"
alias vim="vim -O"
alias vmi="vim -O"

alias cp="cp --interactive"
alias dc="cd"
alias df="df --human-readable"
alias dul="du --human-readable --summarize * | sort --human-numeric-sort --reverse"
alias free="free --mega"
alias loc="locate --database=${HOME}/var/mlocate/mlocate.db"
alias lsof_net="lsof -P -i 4 -n"
alias mount="mount | column -t"
alias mv="mv --interactive"
alias ns="netstat --numeric --tcp --all --udp --program --listening"
alias psc="ps xawf -eo pid,user,cgroup,args"
alias rmdirr="find . -type d -empty -delete"


# calculator
calc()
{
    echo "$*" | bc --mathlib
}


# configure less to show man pages in color
man()
{
    env LESS_TERMCAP_mb=$'\e[1;31m' \
        LESS_TERMCAP_md=$'\e[1;31m' \
        LESS_TERMCAP_me=$'\e[0m' \
        LESS_TERMCAP_se=$'\e[0m' \
        LESS_TERMCAP_so=$'\e[1;44;33m' \
        LESS_TERMCAP_ue=$'\e[0m' \
        LESS_TERMCAP_us=$'\e[1;32m' \
        man "$@"
}
