#!/usr/bin/env bash
# Filename:      etc/bash/bash_profile
# Last modified: 2016.03.05
# This is only executed for bash login shells.


echo "+++ etc/bash/bash_profile"


if [[ -f "${HOME}/etc/bash/bashrc" ]]; then
    source "${HOME}/etc/bash/bashrc"
fi
