#!/usr/bin/env bash
# Filename:      etc/bash/bash_profile
# Last modified: 2016.03.05
# This is only executed for bash login shells.


echo "+++ bash/bash_profile"


if [[ -f "${HOME}/.bashrc" ]]; then
    . "${HOME}/.bashrc"
fi
